# Generated by Django 5.2 on 2025-04-10 10:05

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenBlocklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateTimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('personal_no', models.CharField(max_length=10, unique=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('official', 'Official'), ('institution', 'Institution'), ('other', 'Other')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mantra', models.TextField()),
                ('phone_contact', models.BigIntegerField()),
                ('profile_photo', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HRPersonel',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('personal_no', models.CharField(max_length=10, unique=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_personnels', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='HrProfile',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mantra', models.TextField()),
                ('phone_contact', models.BigIntegerField()),
                ('profile_photo', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hr_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.hrpersonel')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('personal_no', models.CharField(max_length=10, unique=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('approved_by_manager', models.BooleanField(default=False)),
                ('approved_by_hr', models.BooleanField(default=False)),
                ('manager_app_date', models.DateTimeField(blank=True, null=True)),
                ('hr_approval_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('hr_personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hrpersonel')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.leave')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mantra', models.TextField()),
                ('phone_contact', models.BigIntegerField()),
                ('profile_photo', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Remuneration',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('remuneration_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RemunerationDescription',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deduction', 'Deduction'), ('bonus', 'Bonus'), ('allowance', 'Allowance'), ('normal', 'Normal')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('remuneration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.remuneration')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.employee')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overseen_goals', to='core.manager')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.training')),
            ],
        ),
    ]
